export const actionTypes = {
  ADDTODO:"ADDTODO",
  TITLE:"TITLE",
  DETAILS:"DETAILS",
  TAG_INPUT:"TAG_INPUT",
  TAGS:"TAGS",
  STARTDATE:"STARTDATE",
  STARTMONTH:"STARTMONTH",
  STARTYEARS:"STARTYEARS",
  END_DATE:"END_DATE",
  END_MONTH:"END_MONTH",
  END_YEAR:"END_YEAR",
  ADD_TODO_ITEMS:"ADD_TODO_ITEMS"
};
